### ISSUE TITLE
Page title hidden by Topnav on Mobile

### ISSUE THREAD

**Issue by GreyBeard42** [GreyBeard42/greybeard42.github.io#4]
The page title on each of my pages gets hidden by the top navigation bar on mobile.
The Navigation Bar is `position:  fixed;`, so I assume this would need some tricky javascript.

Screenshots:
![Screenshot (59)](https://github.com/user-attachments/assets/bbe9f488-55ba-41a4-9263-6d7a32e0f257)
![Screenshot (58)](https://github.com/user-attachments/assets/64b42ff0-7e31-44c7-aafa-79d2668ce031)

Any help would be great! 😀

**Comment by QaisarMoin** [comment]
Please assign me this issue

**Comment by GreyBeard42** [comment]
👍

**Comment by PRAteek-singHWY** [comment]
@GreyBeard42 assign this issue to me i will give you the resolution within 3hrs

**Comment by PRAteek-singHWY** [comment]
> @GreyBeard42 assign this issue to me please, i will give you the resolution within 3hrs .

@GreyBeard42 sir it's done i have raised a PR , please review it

**Comment by GreyBeard42** [comment]
Works flawlessly. Thank you so much!

**Comment by PRAteek-singHWY** [comment]
> Works flawlessly. Thank you so much!

Welcome Sir
Sir will this be counted towards my hacktoberfest PR

**Comment by GreyBeard42** [comment]
Yes, I believe so.
